project:
  type: website
  resources:
    - "data/episodes/*/clips/*.mp3"

website:
  title: "Radio show: Your Province. Your Premier."
  description: |
    Analysis of healthcare-related content from Alberta Premier Danielle Smith
    on the "Your Province. Your Premier." radio show.

  sidebar:
    style: floating
    search: true
    contents:
      - index.qmd
      - section: "Episodes"
        content:
      - episodes/2025-12-20-your-province-your-premier-12202025.qmd
      - episodes/2025-12-20-your-province-your-premier-12202025_transcript.qmd
      - about.qmd

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    number-sections: false

execute:
  freeze: auto

lang: en-CA

